# Generated by Django 5.2.4 on 2025-08-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='teste',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
